### ISSUE TITLE
I cannot start registry in kubernetes

### ISSUE THREAD

**Issue by jaynakus** [Joxit/helm-charts#16]
unable to configure authorization (htpasswd): failed to open htpasswd path open /etc/registry/.htpasswd: read-only file system

This is the logs in container

```
time="2024-02-09T09:11:58.479810679Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.20.8 instance.id=9b4df9d7-7bec-4718-802e-6c3681a54a6b service=registry version=2.8.3 
2024-02-09T15:11:58.480054823+06:00 time="2024-02-09T09:11:58.479956932Z" level=info msg="redis not configured" go.version=go1.20.8 instance.id=9b4df9d7-7bec-4718-802e-6c3681a54a6b service=registry version=2.8.3 
2024-02-09T15:11:58.480102126+06:00 time="2024-02-09T09:11:58.480008693Z" level=info msg="Starting upload purge in 10m0s" go.version=go1.20.8 instance.id=9b4df9d7-7bec-4718-802e-6c3681a54a6b service=registry version=2.8.3 
time="2024-02-09T09:11:58.480217822Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.20.8 instance.id=9b4df9d7-7bec-4718-802e-6c3681a54a6b service=registry version=2.8.3 
2024-02-09T15:11:58.482513603+06:00 panic: unable to configure authorization (htpasswd): failed to open htpasswd path open /etc/registry/.htpasswd: read-only file system
2024-02-09T15:11:58.482537000+06:00 
2024-02-09T15:11:58.482545484+06:00 goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp({0xf29128?, 0xc0004a5560?}, 0xc0004c6000)
2024-02-09T15:11:58.482570250+06:00 	github.com/docker/distribution/registry/handlers/app.go:314 +0x1c7a
2024-02-09T15:11:58.482589928+06:00 github.com/docker/distribution/registry.NewRegistry({0xf29128?, 0xc0004a4a20?}, 0xc0004c6000)
	github.com/docker/distribution/registry/registry.go:161 +0x145
github.com/docker/distribution/registry.glob..func1(0xc000034190?, {0xc000416f20, 0x1, 0x1})
	github.com/docker/distribution/registry/registry.go:119 +0x18f
2024-02-09T15:11:58.482642685+06:00 github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x14ae1e0, {0xc000416ee0?, 0x2?, 0x2?})
	github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x44f
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x14ae380)
2024-02-09T15:11:58.482707644+06:00 	github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0xaa
2024-02-09T15:11:58.482713374+06:00 main.main()
	github.com/docker/distribution/cmd/registry/main.go:23 +0x25
```

This is the values.yaml

```
registry:
  enabled: true
  image: registry:2
  dataVolume:
    persistentVolumeClaim:
      claimName: 'docker-registry'
  auth:
    basic:
      enabled: true
      realm: Docker registry
      htpasswdPath: /etc/registry/.htpasswd
      secretName: 'registry-auth'
  ingress:
    enabled: true
    host: docker.pay24.asia
    tls:
      - hosts:
          - docker.pay24.asia
        secretName: tls-pay24-asia
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
```

**Comment by jbee43** [comment]
Same... maybe this in `charts/docker-registry-ui/templates/registry-deployment.yaml`
```
volumeMounts:
  ...
  {{- if .Values.registry.auth.basic.enabled }}
  - name: htpasswd
    mountPath: ...
    readOnly: true
```
